# Generated by Django 6.0.5 on 2026-09-11 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="feedtoken",
            name="name",
            field=models.CharField(default="Default feed token", max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
