# Generated by Django 6.0.5 on 2026-08-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bookmark_link_behavior",
            field=models.CharField(
                choices=[("url", "URL"), ("snapshot", "Latest snapshot")],
                default="url",
                max_length=10,
            ),
        ),
    ]
