# Generated by Django 6.0.5 on 2026-07-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0054_bookmarkbundle_filter_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_tag_hashtag',
            field=models.BooleanField(default=True),
        ),
    ]
